### PR TITLE
Add project name and project domain name

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

Adds the project name and project domain name for easing discovery

----

**Related issue :** #186

### CODE REVIEW

**Comment by enolfc** [comment]
Tests are missing...

**Comment by enolfc** [comment]
pushed simple change to retrigger QA

**Comment by gwarf** [comment]
I wonder if we should wait more for the two missing checks... What's your opinion @enolfc ?

**Comment by enolfc** [comment]
> I wonder if we should wait more for the two missing checks... What's your opinion @enolfc ?

codacy is completely optional, can be even removed
jenkins... unsure, are we really using it?

**Review by gwarf — APPROVED** [review]
LGTM

**Comment by gwarf** [comment]
I've re-triggered a build from Travis, let's see...

**Pull request merged**
