### PR TITLE
Avoid use of getchildren

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

This is deprecated in py2.7 and not available in py3

### CODE REVIEW

**Review by gwarf — APPROVED** [review]
Thanks, LGTM!

**Comment by enolfc** [comment]
@gwarf How do we fix all this never completed tests :( ?

**Comment by gwarf** [comment]
So @orviz reached me about the Jenkins part, we will fix it, but in the meantime I've disable dit.
Still we need to have at least the travis part working.
I will also check codacy and potentially disable it too.

**Comment by enolfc** [comment]
travis was happy about this one. Should be restored

**Comment by gwarf** [comment]
I'm a bit confused with the travis-ci.org vs travis-ci.com and all, and not understanding why the status was again not reaching GitHub.
I've removed the travis checks, and I'm no more allowed to add it as it seems it's lacking feedback from travis since too long.
May need to completely redo travis integration for this repo...

**Comment by gwarf** [comment]
OK, I've randomly unticked and reticked some checkboxes here and there, and now we got the status back working...
We may want to test GitHub actions at some point to rely on one less provider for this.

**Pull request merged**
