### PR TITLE
Add the base_mpuri to the other_info

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

Add helpful info to AppDB as OtherInfo

### CODE REVIEW

**Comment by enolfc** [comment]
OpenNebula missing...

**Comment by gwarf** [comment]
> OpenNebula missing...

So should we aim at including it before merging?

**Comment by enolfc** [comment]
> > OpenNebula missing...
> 
> So should we aim at including it before merging?

Yes, but I wanted to have a placeholder for testing with AppDB. For the ONE code I need some input from cloudkeeper yet.

**Comment by enolfc** [comment]
OpenNebula implementation added, ready for final review

**Pull request merged**
