### PR TITLE
Several fixes for OpenNebula (and CentOS 7)

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

Fixes several issues found while testing with OpenNebula providers.

----

**Related issue :** #169

### CODE REVIEW

**Comment by enolfc** [comment]
So far this fixes pre Glue2.1, now found some more issues with Glue2.1, so new changes coming soon

**Comment by enolfc** [comment]
Now working for Glue2.1 and OpenNebula.

**Comment by enolfc** [comment]
I realised there is another place where we use non-default CAs: https://github.com/EGI-Foundation/cloud-info-provider/blob/master/cloud_info_provider/providers/ssl_utils.py#L47

That should be also changed, although I'm not sure if we just do not try to specify CAs there and let python pick whatever the system has or try to use the same as requests library (which may not be system default).

**Comment by gwarf** [comment]
At least all the component should have the same logic but I'm not sure what would be the easiest/cleanest for site admins.

**Pull request merged**
