### PR TITLE
Code style

### PR DESCRIPTION
**Pull request by enolfc**
# Summary 

Enforce code style everywhere

----

**Related issue :** #165

### CODE REVIEW

**Comment by enolfc** [comment]
@orviz, it seems the Dockerfile.build approach has issues in Jenkins:
```
/var/lib/jenkins/workspace/_Code_cloud-info-provider_PR-180@tmp/durable-0d83468b/script.sh: line 1: docker: command not found
```

**Comment by orviz** [comment]
@enolfc it was not defaulting to a slave with docker, working on the weird new error

**Comment by orviz** [comment]
@enolfc working now

**Comment by enolfc** [comment]
Dismiss this one

**Pull request closed without merging**
